### ISSUE TITLE
[BUG] Sandbox failing with Python 3.8

### ISSUE THREAD

**Issue by mariajgrimaldi** [eduNEXT/tutor-contrib-codejail#19]
### **Description**

The codejailservice fails to execute code when using Python 3.8 in the secure sandbox.

### **To Reproduce**
1. Install tutor, tutor-contrib-codejail, [codejailservice](https://github.com/eduNEXT/codejailservice) from source
2. Move to nutmeg branches: nutmeg -for tutor-, 14.0.0 -for codejailservice-, MJG/nutmeg -for tutor-contrib-codejail-
3. Install plugin
4. Build images: tutor config save && tutor images build all
5. Init services: tutor dev init
6. Follow test instructions [here](https://github.com/eduNEXT/tutor-contrib-codejail#how-to-know-if-codejail-is-working). The error will appear in the course component.
Further testing:
7. Enter container: tutor dev dc run codejailservice bash
8. Activate environment: source /sandbox/venv/bin/activate
9. Run `python`, the same error will appear 

### **Additional context**
We encountered this error while giving nutmeg support to the plugin. First, trying to use a Python Evaluated component in a course:
![image(7)](https://user-images.githubusercontent.com/64440265/169817953-75010b13-bd5c-4920-b436-c3670b38d93b.png)

After entering the codejailservice container to inspect contents, we found that running `python` using the sandbox virtualenv failed:
![image(9)](https://user-images.githubusercontent.com/64440265/169818720-498ab1f1-9a6e-46b1-899d-3ee58a327199.png)

With the same error as the course component. Then, we ran the same command but without the docker-compose files:
![image(8)](https://user-images.githubusercontent.com/64440265/169818684-c54862ec-d89c-4741-aac4-1682a6edc7e2.png)

And it worked. So it must be something in the docker-compose configurations. After removing [this](https://github.com/eduNEXT/tutor-contrib-codejail/blob/main/tutorcodejail/patches/local-docker-compose-services#L7) line, the command worked with the docker-compose files. So what's going on with the apparmor profile & python3.8? :thinking: 
For reference, [here is](https://github.com/eduNEXT/tutor-contrib-codejail/blob/main/tutorcodejail/templates/codejail/apps/profiles/docker-edx-sandbox) the appamor profile defined by this plugin.

**Comment by kdmccormick** [comment]
Hey @jmbowman, did you folks see an error of this sort when upgrading edx.org's edx-sandbox environment to Python 3.8?

**Comment by regisb** [comment]
~[A quick search](https://duckduckgo.com/?t=ffab&q=python+init_fs_encoding+failed+to+get+the+encoding+of+the+filesystem&ia=web) (my specialty) yielded this: https://stackoverflow.com/questions/65184937/fatal-python-error-init-fs-encoding-failed-to-get-the-python-codec-of-the-file
Could it all have to do with the PYTHONHOME environment variable? (full disclaimer: I don't know what I'm talking about)~

(now that was a silly idea)

**Comment by jmbowman** [comment]
My first suspicion would be some sort of mismatch with either the Python version set up in the apparmor configuration or the name of the binary being executed, but Ned might have a better idea; I'll point him here.  Also note that we figured out a way to test codejail with apparmor enforced in GitHub Actions, something like that may be useful for CI here also: https://github.com/openedx/codejail/blob/master/.github/workflows/ci.yml .

**Comment by nedbat** [comment]
I don't remember an error like this, but "encodings" I think is the first module imported from the file system, after a few modules imported from frozen modules.  Do all of the directories mentioned in the configuration exist?  You could try adding "-vv" to the Python command line to see all the import activity, which might have some clues.

**Comment by regisb** [comment]
I believe I found the problem: this line was not upgraded to 3.8.5 https://github.com/eduNEXT/tutor-contrib-codejail/blob/c9d0027b53982cb0075b04b3738ac6ffbf1d1a89/tutorcodejail/templates/codejail/apps/profiles/docker-edx-sandbox#L55

On my machine, after I modify this line and reload the apparmor profile (with `tutor dev init --limit=codejail`) I am able to run the python binary from the sandbox venv. You may have to manually delete the existing profile before applying the new one, though.

**Comment by mariajgrimaldi** [comment]
Thank you for the help! Really appreciated! @nedbat  @jmbowman @regisb @kdmccormick :grinning: 

I finally got this working! Regis was totally right! I totally missed that line. Thank you so much. I'm closing this issue now.

**Comment by Abdess** [comment]
The bug seems to be back on Nutmeg (Tutor 14.0.4) with the latest plugin (https://github.com/eduNEXT/tutor-contrib-codejail/commit/ce71496fad6491fa4923c00f11b4650589a91e36) 😅 

![image](https://user-images.githubusercontent.com/3028866/183930371-47d3f541-3c0e-4340-9052-921c5143f69a.png)

![image](https://user-images.githubusercontent.com/3028866/183929300-6e98ba02-0e22-4191-9274-ae46b4e0a352.png)

![image](https://user-images.githubusercontent.com/3028866/183930240-f795bd34-186a-46d5-aa80-761557db2d27.png)

![image](https://user-images.githubusercontent.com/3028866/183930584-8b565482-3d4c-440b-a685-3b0fdce7bd39.png)

**Comment by mariajgrimaldi** [comment]
Hello @Abdess! Can you try removing the app armor profile & creating it again with the nutmeg version of this plugin?

**Comment by Abdess** [comment]
Hello @mariajgrimaldi! :)
The error persists. 🤔 

In case of doubt, you are talking about this [file](https://github.com/eduNEXT/tutor-contrib-codejail/blob/nutmeg/tutorcodejail/templates/codejail/apps/profiles/docker-edx-sandbox), right?

**Comment by mariajgrimaldi** [comment]
Yes! @Abdess, I was referring to the profile created using that file. Can you list how did you get to that error? To see if I can reproduce it. Thanks (include all possible details) :smile:

**Comment by Abdess** [comment]
> Yes! @Abdess, I was referring to the profile created using that file. Can you list how did you get to that error? To see if I can reproduce it. Thanks (include all possible details) 😄

For the details, it will be relatively short, because I just followed the README. 😅 

I use Tutor 14.0.4 with Nutmeg.

Here are the steps performed:
- `pip install git+https://github.com/edunext/tutor-contrib-codejail`
- `tutor plugins enable codejail`
- `tutor config save`
- `tutor local init --limit=codejail`
- `tutor local quickstart`
- Test with course_codejail_example.tar.gz
- > error

I stay available to answer all your questions.

**Comment by mariajgrimaldi** [comment]
Thanks again @Abdess; I have a few questions:

1. Was this the first time you installed this plugin & created the app armor profile?
2. Did you remove the app armor profile and add it again? 

This might again have something to do with the current profile you're using.

**Comment by Abdess** [comment]
You're welcome @mariajgrimaldi; To answer the questions:
1. Yes, it was a fresh install.
2. Yes, one interesting thing is that there was no difference between the 2 files.

I stay tuned if you have any manipulations to suggest.
