### ISSUE TITLE
[Bug] Missing docker image?

### ISSUE THREAD

**Issue by drhodes** [eduNEXT/tutor-contrib-codejail#27]
Hi, does the 14.1.0 image needs to be pushed to dockerhub? I couldn't find it over on this site:
https://hub.docker.com/r/overhangio/openedx/tags
_(by the way I don't have a ton of docker experience)_

**Describe the bug**
Installing tutor-contrib-codejail failed

**To Reproduce**
1) follow install directions for tutor
2) follow install directions for tutor-contrib-codejail

**Expected behavior**
tutor-contrib-codejail should install :)

**Additional context**

After tutor-contrib-codefail failed to install, I manually edited this Dockerfile 

`~/.local/share/tutor/env/plugins/codejail/build/codejail/Dockerfile`

Line 31:

`RUN git clone https://github.com/eduNEXT/codejailservice.git --branch 14.1.0 --depth 1 /openedx/codejailservice`

Then decremented the version number to `14.0.0`

`RUN git clone https://github.com/eduNEXT/codejailservice.git --branch 14.0.0 --depth 1 /openedx/codejailservice`

then the install worked as expected.

**System**

```bash
$ uname -a
Linux sneaker 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

$ tutor --version
tutor, version 14.0.5
```

----
I got this working for me, so please close this issue if it makes sense to do so, I thought it might help someone, thanks!

**Comment by mariajgrimaldi** [comment]
Hello @drhodes! Thanks for reaching out. In fact, after installing this plugin it will try to download the image of the codejailservice with tag v14.1.0, so it would fail since it didn't exist. Thanks to your report, we created a new one! Please let me know if it works for you now.

**Comment by drhodes** [comment]
Ok, I just tested it - works as expected, thanks @mariajgrimaldi !
