### ISSUE TITLE
["BUG"] Import Error while importing a python library .STDERR ,STDOUT #17["BUG"]

### ISSUE THREAD

**Issue by babarlhr** [eduNEXT/tutor-contrib-codejail#29]
# Problem 
I have installed a stack of OpexEDX platform using Tutor and installed OpexEdx "Codejail" plugin using below link 

`pip install git+https://github.com/edunext/tutor-contrib-codejail`

https://github.com/eduNEXT/tutor-contrib-codejail

I am facing a problem during working on the code jail while importing python matplotlib library.

importing the same library inside codejail container is working fine. the only problem is import through OpnexEdx code block.   > advance black > problem.
I have already installed the Codejail and Matplotlib on docker. 

I have to run this code. which gives error

```
<problem>
<script type="loncapa/python">
import matplotlib
</script>
</problem>
```

`import os` works fine
but getting error while
`import matplotlib`

detail of current stack: 
- open edx version : openedx-mfe:14.0.1 
- code jail version :  codejailservice:14.1.0 
- please see the error message below 

`
cannot create LoncapaProblem block-v1:VUP+Math101+2022+type@problem+block@3319c4e42da64a74b0e40f048e3f2599: Error while executing script code: Couldn't execute jailed code: stdout: b'', stderr: b'Traceback (most recent call last):\n  File &#34;jailed_code&#34;, line 19, in <module>\n    exec(code, g_dict)\n  File &#34;<string>&#34;, line 66, in <module>\n  File &#34;/sandbox/venv/lib/python3.8/site-packages/matplotlib/__init__.py&#34;, line 921, in <module>\n    dict.update(rcParams, rc_params_in_file(matplotlib_fname()))\n  File &#34;/sandbox/venv/lib/python3.8/site-packages/matplotlib/__init__.py&#34;, line 602, in matplotlib_fname\n    for fname in gen_candidates():\n  File &#34;/sandbox/venv/lib/python3.8/site-packages/matplotlib/__init__.py&#34;, line 599, in gen_candidates\n    yield os.path.join(get_configdir(), \'matplotlibrc\')\n  File &#34;/sandbox/venv/lib/python3.8/site-packages/matplotlib/__init__.py&#34;, line 239, in wrapper\n    ret = func(**kwargs)\n  File &#34;/sandbox/venv/lib/python3.8/site-packages/matplotlib/__init__.py&#34;, line 502, in get_configdir\n    return get_config_or_cache_dir(_get_xdg_config_dir())\n  File &#34;/sandbox/venv/lib/python3.8/site-packages/matplotlib/__init__.py&#34;, line 474, in get_config_or_cache_dir\n    tempfile.mkdtemp(prefix=&#34;matplotlib-&#34;)\n  File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 347, in mkdtemp\n    prefix, suffix, dir, output_type = sanitize_params(prefix, suffix, dir)\n  File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 117, in sanitize_params\n    dir = gettempdir()\n  File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 286, in gettempdir\n    tempdir = get_default_tempdir()\n  File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 218, in _get_default_tempdir\n    raise FileNotFoundError(_errno.ENOENT,\nFileNotFoundError: [Errno 2] No usable temporary directory found in [\'/tmp\', \'/var/tmp\', \'/usr/tmp\', \'/tmp/codejail-lbfd69da\']\n' with status code: 1. For more information check Codejail Service logs.
`

Codejail service logs are as follows: 

`{"log":"[pid: 6|app: 0|req: 20/39] 172.18.0.10 () {36 vars in 483 bytes} [Tue Nov 22 11:24:59 2022] POST /api/v0/code-exec =\u003e generated 1978 bytes in 742 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)\n","stream":"stderr","time":"2022-11-22T11:25:00.151315626Z"}
{"log":"2022-11-22 11:26:23,304 INFO 9 [codejailservice.app] code_exec_service.py:52 - Running problem_id:53fbaa04859f41989ab967c15a12c013 jailed code for course_id:course-v1:VUP+Math101+2022 ...\n","stream":"stderr","time":"2022-11-22T11:26:23.30489438Z"}
{"log":"2022-11-22 11:26:23,343 INFO 9 [codejailservice.app] code_exec_service.py:73 - Jailed code was executed in 0.03849988000001758 seconds.\n","stream":"stderr","time":"2022-11-22T11:26:23.343618965Z"}
{"log":"[pid: 9|app: 0|req: 20/40] 172.18.0.10 () {36 vars in 483 bytes} [Tue Nov 22 11:26:23 2022] POST /api/v0/code-exec =\u003e generated 73 bytes in 40 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)\n","stream":"stderr","time":"2022-11-22T11:26:23.344178308Z"}
{"log":"2022-11-23 04:15:24,786 INFO 6 [codejailservice.app] code_exec_service.py:52 - Running problem_id:3319c4e42da64a74b0e40f048e3f2599 jailed code for course_id:course-v1:VUP+Math101+2022 ...\n","stream":"stderr","time":"2022-11-23T04:15:24.786287416Z"}
{"log":"2022-11-23 04:15:25,582 ERROR 6 [codejailservice.app] code_exec_service.py:70 - Error found while executing jailed code.\n","stream":"stderr","time":"2022-11-23T04:15:25.582527974Z"}
{"log":"[pid: 6|app: 0|req: 21/41] 172.18.0.10 () {36 vars in 483 bytes} [Wed Nov 23 04:15:24 2022] POST /api/v0/code-exec =\u003e generated 1978 bytes in 798 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)\n","stream":"stderr","time":"2022-11-23T04:15:25.583132326Z"}
{"log":"2022-11-23 06:00:15,150 INFO 9 [codejailservice.app] code_exec_service.py:52 - Running problem_id:3319c4e42da64a74b0e40f048e3f2599 jailed code for course_id:course-v1:VUP+Math101+2022 ...\n","stream":"stderr","time":"2022-11-23T06:00:15.15073834Z"}
{"log":"2022-11-23 06:00:15,891 ERROR 9 [codejailservice.app] code_exec_service.py:70 - Error found while executing jailed code.\n","stream":"stderr","time":"2022-11-23T06:00:15.8916806Z"}
{"log":"[pid: 9|app: 0|req: 21/42] 172.18.0.10 () {36 vars in 483 bytes} [Wed Nov 23 06:00:15 2022] POST /api/v0/code-exec =\u003e generated 1978 bytes in 742 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)\n","stream":"stderr","time":"2022-11-23T06:00:15.892225441Z"}`

# WorkAround (Temporary)

After diagnosing, I have found that this is because of  **AppArmor**  loaded profile.  AppArmor was denying to write **temp** files which were produced during `import matplotlib` .

>  get_configdir\n return get_config_or_cache_dir(_get_xdg_config_dir())\n File &#34;/sandbox/venv/lib/python3.8/site-packages/matplotlib/__init__.py&#34;, line 474, in get_config_or_cache_dir\n tempfile.mkdtemp(prefix=&#34;matplotlib-&#34;)\n File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 347, in mkdtemp\n prefix, suffix, dir, output_type = sanitize_params(prefix, suffix, dir)\n File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 117, in sanitize_params\n dir = gettempdir()\n File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 286, in gettempdir\n tempdir = get_default_tempdir()\n File &#34;/opt/pyenv/versions/3.8.6_sandbox/lib/python3.8/tempfile.py&#34;, line 218, in _get_default_tempdir\n raise FileNotFoundError(_errno.ENOENT,\nFileNotFoundError: [Errno 2] No usable temporary directory found in [\'/tmp\', \'/var/tmp\', \'/usr/tmp\', \'/tmp/codejail-lbfd69da\']\n' with status code: 1. For more information check Codejail Service logs.

 AppArmor loaded ' [docker-edx-sandbox](https://github.com/eduNEXT/tutor-contrib-codejail/blob/main/tutorcodejail/templates/codejail/apps/profiles/docker-edx-sandbox) ' which in my case was stored in `/etc/apparmor.d/docker-edx-sandbox`  directory.  docker container of Sandbox service was using that profile.

to view this I used `dmesg` command with root privileges to view the logs produced by `AppArmor `. whcih shows the current profile used by Sandbox container service => 'docker-edx-sandbox'. Logs of dmesg show **Mkdir command: access denied**   by `AppArmor`. 

 Temporarily Workaround of this issue I have **Removed**  the loaded AppArmor profile from memory by the below command.

`sudo apparmor_parser -R /etc/apparmor.d/docker-edx-sandbox`

**Important Note**  : Don't use in production .it will **bypass** AppArmor security by removing the profile from the kernel.

We Need to update `https://github.com/eduNEXT/tutor-contrib-codejail/blob/main/tutorcodejail/templates/codejail/apps/profiles/docker-edx-sandbox`   template for allowing creating temp files in sandbox environment

**Comment by mariajgrimaldi** [comment]
Thanks for the report! I'll be checking this out asap!

**Comment by MoisesGSalas** [comment]
I'm still not quite sure why this is happening.

The [current rules](https://github.com/eduNEXT/tutor-contrib-codejail/blob/main/tutorcodejail/templates/codejail/apps/profiles/docker-edx-sandbox#L56-L57) allow to write to any subdirectory of a any directory with the prefix `/tmp/codejail-`. The codejail library creates a [temp dir](https://github.com/openedx/codejail/blob/2c66dde0601b2315cc76a56ac7d89c249ec0bea4/codejail/util.py#L15) with this prefix and [runs the command from there](https://github.com/openedx/codejail/blob/master/codejail/jail_code.py#L317). If I try to create a temp directory using the `/sandbox/venv/bin/python` binary I will get an error unless my current working directory is `/tmp/codejail-somerandomhash/` (which is the expected behaviour).

I will try to investigate further on why the jailed code isn't being run from were is supposed to.

**Comment by mariajgrimaldi** [comment]
@MoisesGSalas and I were testing and found that the profile execution mode used ([Cx](https://gitlab.com/apparmor/apparmor/-/wikis/manpage_apparmor.d.5#access-modes-details)) cleans the environment variables from the parent environment before the child process inherits it. Among these variables is `TMPDIR`, which indicates [where temporary files are expected to be created](https://github.com/python/cpython/blob/426b022776672fdf3d71ddd98d89af341c88080f/Lib/tempfile.py#L170). That's why the process can't create new temp files.

A possible solution could be to change the policy access from Cx to cx, but according to [some documentation](https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-apparmor-profiles.html#sec-apparmor-profiles-exec-clean), that would mean a security risk.

Given that we're close to a new plugin release (Olive), we propose to make this change later when the release is stable.

**Comment by mariajgrimaldi** [comment]
Also, FYI:

I thought this was related to our latest upgrades. But after researching a bit more with my team, we realized we'd had that issue since the Lilac release, i.e, it has never worked 😅 .

**Comment by santiagosuarezedunext** [comment]
@babarlhr Did you manage to do what you wanted somehow without using matplotlib?

**Comment by babarlhr** [comment]
> @babarlhr Did you manage to do what you wanted somehow without using matplotlib?

@santiagosuarezedunext I have managed to import matplotlib using the above Workaround (Temporary) by removing the apparmour Profile :

`
sudo apparmor_parser -R /etc/apparmor.d/docker-edx-sandbox
`

 but I have to use matplotlib anyway because some of my coworkers needed this library to Draw images and calculation. Example code is below :
 
 ```
<problem>
<script type="loncapa/python">
from random import randint
import random
import math
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from math import cos, sin, acos, sqrt, atan2
import io
import base64


def compare(f1,f2,tol=0.1):
  return abs(f1 - f2) &lt; tol
     
def test_answer(expected,answer): 
  return compare(eval(answer.strip()),float(expected.strip()))
    

c1 = randint (-3,3)
c2 = randint (-3,3)
(Cx, Cy) = (c1,c2)
r = randint (3,6) 
a = r
(P1x,P1y) = (c1+r,c2)  # point 1 on the circumfrence
(P2x,P2y) = (c1,c2+r)  # point 2 on the circumfrence
# Example values


  

(Px, Py) = (-10, 10)

Px_m = -Px
Px_m_s = str(Px_m)
if Px_m &gt;0:
  Px_m_s = "+"+Px_m_s

Py_m = -Py
Py_m_s = str(Py_m)
if Py_m &gt;0:
  Py_m_s = "+"+Py_m_s

x = [Px,Cx]
y = [Py,Cy]

b = round(sqrt((Px - Cx)**2 + (Py - Cy)**2),2)  # hypot() also works here
th = round(acos(a / b),2)  # angle theta
slope_PC = round((Py - Cy)/ (Px - Cx),2)
d = round(atan2(Py - Cy, Px - Cx),2)  # direction angle of point P from C
d1 = d + th  # direction angle of point T1 from C
d2 = d - th  # direction angle of point T2 from C

T1x = round(Cx + a * cos(d1),2)
T1y = round(Cy + a * sin(d1),2)
T2x = round(Cx + a * cos(d2),2)
T2y = round(Cy + a * sin(d2),2)

x_tan1 = [Px,T1x]
y_tan1 = [Py,T1y]

x_tan2 = [Px,T2x]
y_tan2 = [Py,T2y]

x_all = [Px,Cx,T1x,T2x]
y_all = [Py,Cy,T1y,T2y]

x_CA = [Cx,T1x]
y_CA = [Cy,T1y]

x_CB = [Cx,T2x]
y_CB = [Cy,T2y]

circle= plt.Circle((Cx,Cy), radius= a,color='black', fill=False)
fig = plt.figure(figsize=(4,4))
ax=plt.gca()
ax.add_patch(circle)
ax.plot(x,y)
ax.plot(x_tan1,y_tan1)
ax.plot(x_tan2,y_tan2)
ax.plot(x_CA,y_CA)
ax.plot(x_CB,y_CB)
ax.scatter(x_all,y_all)
ax.axis('scaled')
ax.grid(which='both', linestyle='dotted', linewidth=0.1, color='black')


ax.text(T1x, T1y, "A", fontsize=18, horizontalalignment='left', verticalalignment='top')
ax.text(T2x, T2y, "B", fontsize=18, horizontalalignment='left', verticalalignment='top')
ax.text(Px, Py, "P", fontsize=18, horizontalalignment='left', verticalalignment='top')
ax.text(Cx, Cy, "C", fontsize=18, horizontalalignment='left', verticalalignment='top')

buf = io.BytesIO()
fig.savefig(buf, format='png')
buf.seek(0)
figstr = base64.b64encode(buf.read())  

</script>
  <p>  Given a circle with center  \( C = ($Cx, $Cy) \), radius \( r = $a \) and point two points   \( P_1 = ($P1x,$P1y) \) and  \( P_2 = ($P2x,$P2y) \), find mid point \( M \) of chord \( P_1 P_2 \) to the given circle and point \( R \) where tangents to points \( P_1 \) and \( P_2 \) intersect.</p>
  <table>
    <tbody>
      <tr>
        <td> </td>
        <td> x coordinate </td>
        <td> y coordinate </td>
      </tr>
      <tr>
        <td>Point M</td>
        <td>
          <numericalresponse answer="$T1x">
            <responseparam type="tolerance" default="0.01%" name="tol" description="Numerical Tolerance"/>
            <textline size="10"/>
          </numericalresponse>
        </td>
        <td>
          <numericalresponse answer="$T1y">
            <responseparam type="tolerance" default="0.01%" name="tol" description="Numerical Tolerance"/>
            <textline size="10"/>
          </numericalresponse>
        </td>
      </tr>
      <tr>
        <td>Point R</td>
        <td>
          <numericalresponse answer="$T2x">
            <responseparam type="tolerance" default="0.01%" name="tol" description="Numerical Tolerance"/>
            <textline size="10"/>
          </numericalresponse>
        </td>
        <td>
          <numericalresponse answer="$T2y">
            <responseparam type="tolerance" default="0.01%" name="tol" description="Numerical Tolerance"/>
            <textline size="10"/>
          </numericalresponse>
        </td>
      </tr>
    </tbody>
  </table>
  <solution>
    <p>
      <img src="data:image/png;base64,$figstr"/>
    </p>
    <p> Length of line segment AC is equal to radius of given circle, |AC| = \( $a \) </p>
    <p> Length of line segment PC can be calculated from oordinates of points P and C.  |PC| = \( $b \) </p>
    <p> Slope \( m \) of line segment PC can also be computed from points P and C, \(m = $slope_PC \) </p>
    <p> \( \alpha = {tan}^ {-1} (m) = $d \) is the angle line segment PC make with x-axis </p>
    <p> Let  angle CPA \(  =\theta  \), we can compute   \( \theta = {cos} ^ {-1} (\frac {|AC|}{|PC|}) = $th \) </p>
    <p> Let \( \beta  \) be the angle line segment PA makes with x-axis, then \( \beta = \alpha + \theta \) </p>
    <p> x-coordinate of point A = x-coordinate of center of the circle + |AC| * cos ( \( \beta \) )</p>
    <p> y-coordinate of point A = y-coordinate of center of the circle + |AC| * sin ( \( \beta \)) </p>
  </solution>
</problem>


```

**Comment by santiagosuarezedunext** [comment]
I am going to move this issue to in progress it will be attend in the following sprints, thanks for the patience

**Comment by MaferMazu** [comment]
We are working on this issue; when we have a solution or workaround, we will tell you @babarlhr

**Comment by MaferMazu** [comment]
This PR #36 resolves the "No usable temporary directory" problem, but importing matplotlib we still have a problem.

Now I have a permission error:
![Screenshot from 2023-05-14 18-02-40](https://github.com/eduNEXT/tutor-contrib-codejail/assets/35668326/049567e5-11a0-4f3c-9291-1b6b4acb121a)

**Comment by MaferMazu** [comment]
I tried to resolve the permission error but didn't find anything.
For now, a workaround that works is to change the child profile from Cx to cx, understanding the risk [here](https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-apparmor-profiles.html#sec-apparmor-profiles-exec-clean), as @mariajgrimaldi said. However, you need to understand that with that change, you are going to maintain these [variables](https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-apparmor-profiles.html#sec-apparmor-profiles-exec-variables).

This is the update I have for you right now, @babarlhr. Sorry for not being more helpful.

**Comment by MaferMazu** [comment]
I will close this issue.

You can find in [this comment](https://github.com/eduNEXT/tutor-contrib-codejail/pull/36#issuecomment-1563013687) what is happening with matplotlib.

I would love to provide you with a solution instead of a workaround, but we won't do it for now.

The workaround here is to change the child profile from Cx to cx, as I mentioned in the previous comment.
