### ISSUE TITLE
Are the instructions for Olive still valid?

### ISSUE THREAD

**Issue by sambapete** [eduNEXT/tutor-contrib-codejail#33]
Tried running
tutor local init --limit=codejail

But I got
Error: No such command 'init'.

tutor v15.2.0

**Comment by sambapete** [comment]
I tried launching 
tutor local launch

but I got the following error messages after it tried to download the codejail container

```
ERROR: for tutor_local_codejailservice_1  Cannot start service codejailservice: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown

ERROR: for codejailservice  Cannot start service codejailservice: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown
```

And that is most probably because I couldn't do the init part initially...

**Comment by sambapete** [comment]
It seems you need to upgrade the instructions starting with Olive at least:

`tutor local do init --limit=codejail`

**Comment by tedxajce** [comment]
@sambapete , its still an error after doing ```tutor local do init --limit=codejail```

**Comment by zameel7** [comment]
@sambapete , its still an error after doing ```tutor local do init --limit=codejail```

**Comment by mariajgrimaldi** [comment]
Hello there! Sorry for the delay. @sambapete you're absolutely right! We should update the readme with:
`tutor local do init --limit codejail` which should be executed before starting the container.

**Comment by mariajgrimaldi** [comment]
@zameel7: let us know if this worked for you.

**Comment by zameel7** [comment]
@mariajgrimaldi 
I still do get an error

I installed the plugin, enabled it, saved tutor config and then the error pops up saying,
```PermissionError: [Errno 13] Permission denied: '/home/zameel/.local/share/tutor/env/plugins/codejail/apps/config' ```

**Comment by mariajgrimaldi** [comment]
@zameel7: I closed this since this issue was already resolved. Does your user have the correct permissions on the env folder? You could regenerate the environment altogether. If the issue with codejail persists, could you open a new GH issue? Thanks!
