### ISSUE TITLE
["BUG"] Unbale to load the Python Library from Locanda in codejail 

### ISSUE THREAD

**Issue by MSkhaliq** [eduNEXT/tutor-contrib-codejail#35]
I have successfully installed Pybryt inside the Codejail container by running the command `tutor dev dc run codejailservice bash` and then using the `pip install pybryt` command inside the container's library. I was able to confirm that Pybryt was installed by importing it without any issues.

However, when I tried to run the same code outside of the container, in Locanda, I encountered an error with the following error message.

open edx version : `openedx-mfe:14.0.1`
code jail version : `codejailservice:14.1.0`
Python Version : `3.8.10`
Pybryt Version : `0.7.0`
 

code
```
<problem>
<script type="loncapa/python">
import pybryt
</script>   
</problem>
```
Error:
```
cannot create LoncapaProblem block-v1:VU+101+101+type@problem+block@fb44fa0af132469d8d94869b3f15112a: Error while executing script code: Couldn&#39;t execute jailed code: stdout: b&#39;&#39;, stderr: b&#39;Traceback (most recent call last):\n  File &#34;jailed_code&#34;, line 19, in &lt;module&gt;\n    exec(code, g_dict)\n  File &#34;&lt;string&gt;&#34;, line 66, in &lt;module&gt;\nImportError: No module named \&#39;pybryt\&#39;\n&#39; with status code: 1. For more information check Codejail Service logs.
```

**Comment by MSkhaliq** [comment]
Dear @MaferMazu @mariajgrimaldi ,

Greetings, I truly hope it treats you awesomely on your side of the screen :) 

Any solution for the mentioned problem?

I am waiting anxiously for your kind response.

**Comment by mariajgrimaldi** [comment]
@MSkhaliq: hello there! This also happens with the matplotlib library, so we're currently studying a solution for this kind of cases, including yours. Thanks for your patience! 

In the midtime, you can find a temporary workaround in [this comment](https://github.com/eduNEXT/tutor-contrib-codejail/issues/29#issuecomment-1489752478). Let me know if it works for you.

**Comment by mariajgrimaldi** [comment]
cc @santiagosuarezedunext

**Comment by MSkhaliq** [comment]
@mariajgrimaldi , Hi there ! sound good please share the solution as soon as possible. 

unfortunately the mentioned commend not work in my case.

**Comment by santiagosuarezedunext** [comment]
I am going to move this issue to in progress it will be attend in the following sprints, thanks for the patience

**Comment by MSkhaliq** [comment]
Dear @santiagosuarezedunext , 

I hope you are doing great! Any update on the issue ?

**Comment by MaferMazu** [comment]
Hello @MSkhaliq, this issue just entered our sprint. Currently, we are working on this. When we have some updates, we will let you know.

cc @JuanDavidBuitrago

**Comment by MSkhaliq** [comment]
Dear @MaferMazu ,

Thank you for your kind feedback.

**Comment by MSkhaliq** [comment]
Dear @MaferMazu,

I hope you are doing fantastic, Please provide an update on the status of the issue as it has been several days. 

Thanks and regards

**Comment by MaferMazu** [comment]
Sorry for the late response @MSkhaliq.

For installing pybryt, you need to install it in `/sandbox/venv` inside the codejail service.

What worked for me was:
1. Add the requirement in the Dockerfile
    For testing proposes, I edit env/plugins/codejail/build/codejail/Dockerfile
![Screenshot from 2023-05-14 19-13-17](https://github.com/eduNEXT/tutor-contrib-codejail/assets/35668326/047ed51f-304c-4894-b6c2-e07221a04fb2)
2. Build the image: `tutor images build codejail` (In this step, you won't get a "No module named" error, but you are going to have a "No usable directory" error)
3. To fix the "no usable directory" error, follow the instructions here #36.

I tried to enter the codejail bash, activate the venv: `source /sandbox/venv/bin/activate`, and install pybryt: `pip install pybyrt`; but that didn't work for me.

Please let me know if this helps you.

**Comment by MSkhaliq** [comment]
Dear @MaferMazu , 

**You may see all of the steps I took to implement your intended solution, but the problem will not be resolved here.**
1 - In the codejail service installed the Pybryt 
 
![codejailservices](https://github.com/eduNEXT/tutor-contrib-codejail/assets/31242307/132acebc-21c9-478f-9681-22531c14a4fd)
2 - I edit env/plugins/codejail/build/codejail/Dockerfile 
**Note :**On Dev Server I am using` openedx :13.3.1` so the code as per my edx version.

![docker file](https://github.com/eduNEXT/tutor-contrib-codejail/assets/31242307/f5a709fd-0004-4c09-a643-f275bde86180)
3 - Build the image: `tutor images build codejail` successfully without any error

![tutor images build codejail](https://github.com/eduNEXT/tutor-contrib-codejail/assets/31242307/09fbf9c9-74d8-480c-9f3d-edffbf25378b)
4 - Simple code for import the pybryt lib for testing 
`<problem><script type="loncapa/python">import Pybryt</script> </problem>`
5 - Getting the same error 

![Error](https://github.com/eduNEXT/tutor-contrib-codejail/assets/31242307/34d69c8a-ed0b-4479-8e67-55e63f4e6988)

Please do the needful in this regard issue not fixed yet.

Thanks and Regards

**Comment by MaferMazu** [comment]
Hello, @MSkhaliq did you try importing `pybryt` with p in lowercase inside Loncapa problem?

**Comment by MSkhaliq** [comment]
Hi, @MaferMazu Yes here you can see the error 
![error](https://github.com/eduNEXT/tutor-contrib-codejail/assets/31242307/7c80b960-297f-43dc-9fdd-e4004fb4afa5)

**Comment by MaferMazu** [comment]
Hello @MSkhaliq, this issue closed with the merge of the PR.

Regarding your problem and the screenshot you provided, it seems unrelated to the initial issue:
- Install and import pybryt
- Resolve the error you had:
`cannot create LoncapaProblem block-v1:VU+101+101+type@problem+block@fb44fa0af132469d8d94869b3f15112a: Error while executing script code: Couldn&#39;t execute jailed code: stdout: b&#39;&#39;, stderr: b&#39;Traceback (most recent call last):\n  File &#34;jailed_code&#34;, line 19, in &lt;module&gt;\n    exec(code, g_dict)\n  File &#34;&lt;string&gt;&#34;, line 66, in &lt;module&gt;\nImportError: No module named \&#39;pybryt\&#39;\n&#39; with status code: 1. For more information check Codejail Service logs.`.

From what I can gather from your output, it appears to be a syntax error.
