### ISSUE TITLE
version 13.1.0 

### ISSUE THREAD

**Issue by cafuchs** [eduNEXT/tutor-contrib-codejail#4]
Hi
Installing 
  pip install --force-reinstall   git+https://github.com/edunext/tutor-contrib-codejail 
in tutor 13.1.0 replaces tutor to version 12.2.0 and elasticsearch hangs.

Adding a **_Custom Python-Evaluated Input_** problem results in an error:
![image](https://user-images.githubusercontent.com/6151883/149168376-cdc8d682-809e-4a5c-8473-ed88b58f21ee.png)

Can you help me?

Best wishes 
Christoph

**Comment by felipemontoya** [comment]
@JuanDavidBuitrago you will soon take on some of this work and I thought I should raise your awareness of this issue.

@cafuchs sorry for the long wait, this issue was not in my radar and this project has had a recent change of maintainer internally. We'll get back to you soon.

**Comment by felipemontoya** [comment]
This was mentioned at https://github.com/overhangio/2u-tutor-adoption/issues/19#issuecomment-1030084244 and for me, it raises the issue of how do we test this so that we notice the lack of support when the new version is published way before it becomes a blocker for the community.

**Comment by JuanDavidBuitrago** [comment]
This issue was resolved in this PR: https://github.com/eduNEXT/tutor-contrib-codejail/pull/2

**Comment by cafuchs** [comment]
@JuanDavidBuitrago:  Works perfectly - thank you 👍
