### ISSUE TITLE
["BUG"] `tutor.py` is not being used.

### ISSUE THREAD

**Issue by MoisesGSalas** [eduNEXT/tutor-contrib-codejail#44]
**Describe the bug**
This plugins defines a `tutor.py` file that allows you to override the default configuration of the service, this pattern is also used in other Tutor plugins (e.g. [`tutor-notes`](https://github.com/overhangio/tutor-notes/blob/43af20751e6fa86785bbcc32538948661d150848/tutornotes/templates/notes/apps/settings/tutor.py#L49)). Even though the `tutor.py` file is mounted in the container ([`local-docker-compose-services`](https://github.com/eduNEXT/tutor-contrib-codejail/blob/ede19c8ec486966505f37267c1ce538e504feb4a/tutorcodejail/patches/local-docker-compose-services#L11)) it's [not actually being used by the service](https://github.com/eduNEXT/codejailservice/blob/main/codejailservice/app.py#L60). In order to make use of the file we would need to set the environment variable `FLASK_APP_SETTINGS` to use the `tutor.py` module in the container definition.

Additionally we would need to use a new patch similar to [`notes-settings`](https://github.com/overhangio/tutor-notes/blob/master/tutornotes/templates/notes/apps/settings/tutor.py#L49) that allows us to override [the default settings of the service.](https://github.com/eduNEXT/codejailservice/blob/main/codejailservice/config.py#L13-L37).

**To Reproduce**
1. Manually edit the `tutor.py` file and alter the default configuration (see description message)
2. Inside the container run `flask shell`
3. Check the values by running `app.config['CODE_JAIL']` in the shell.
4. None of the values were overriden.

**Expected behavior**
Is possible to modify the default values of the codejail service.

**Comment by MaferMazu** [comment]
@MoisesGSalas, thanks for reporting this; I will add it to the backlog for future prioritizing.
