### ISSUE TITLE
["FEAT"] 🌲 Add Redwood Support (~May)

### ISSUE THREAD

**Issue by MaferMazu** [eduNEXT/tutor-contrib-codejail#50]
**Is your feature request related to a problem? Please describe.**
The release cut is in April, and we want to have a Redwood version of this plugin so the BTR can test the release correctly.

**Describe the solution you'd like**
Having a release or at least a branch with Redwood support.

**Describe alternatives you've considered**
N/A

**Additional context**
Release schedule: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3613392957/Open+edX+Release+Schedule

**Comment by MaferMazu** [comment]
I will change this to May because the release schedule changed: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3613392957/Open+edX+Release+Schedule

**Comment by DawoudSheraz** [comment]
@MaferMazu Hello. Just to catch up on this, are there any significant changes expected in this plugin for redwood? We(Edly) would be needing this plugin updated when/before the release branches are out (important for sandbox https://github.com/overhangio/openedx-release-demo/). At this moment, nightly branch does not have any updates which makes me wonder if the plugin have had any major upgrade. Please let me know if there are any questions. Thanks

**Comment by MaferMazu** [comment]
Hello @DawoudSheraz, when would you need version 18 to be available?

I was thinking of adding the fix for #44 before creating v18, but if we need it before, it is not a problem.
We have #44 and #45 in mind for the next sprints, but they are not release blockers.

**Comment by DawoudSheraz** [comment]
Having the branch available when the cut is made would be good. This will allow the sandbox to include this plugin. You can keep working on the issues if they are expected to take a bit longer.

**Comment by MaferMazu** [comment]
Ok perfect.
I just remember that we will need this PR for Redwood: #52

**Comment by MoisesGSalas** [comment]
Hi @DawoudSheraz, I expect some additional changes to the plugin, in particular related to the sandbox upgrade to python3.11: (https://github.com/openedx/edx-platform/tree/master/requirements/edx-sandbox).

I would try to have the redwood branch up between today and Monday.

**Comment by DawoudSheraz** [comment]
> Hi @DawoudSheraz, I expect some additional changes to the plugin, in particular related to the sandbox upgrade to python3.11: (https://github.com/openedx/edx-platform/tree/master/requirements/edx-sandbox).
> 
> I would try to have the redwood branch up between today and Monday.

No worries, thank you for the update.
