### ISSUE TITLE
["BUG"] Docker Apparmon

### ISSUE THREAD

**Issue by nachoUC3M** [eduNEXT/tutor-contrib-codejail#57]
# tutor local launch

 ⠦ Container tutor_local-codejailservice-1  Starting                                                                                                                                           1.6s

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown

**Comment by mariajgrimaldi** [comment]
Hi there, @nachoUC3M. Thanks for the report! Have you tried running `tutor local do init --limit codejail` before `tutor local launch`? https://github.com/eduNEXT/tutor-contrib-codejail?tab=readme-ov-file#usage

@MoisesGSalas: could you give us a hand here?

**Comment by MoisesGSalas** [comment]
@nachoUC3M, in addition to what @mariajgrimaldi, can you also fill some extra details of your system:

- Operating system.
- Docker version.
- Tutor version.
- tutor-contrib-codejail version

**Comment by nachotheix** [comment]
> Hi there, @nachoUC3M. Thanks for the report! Have you tried running `tutor local do init --limit codejail` before `tutor local launch`? https://github.com/eduNEXT/tutor-contrib-codejail?tab=readme-ov-file#usage
> 
> @MoisesGSalas: could you give us a hand here?

It works. Thanks

**Comment by nachotheix** [comment]
> @nachoUC3M, in addition to what @mariajgrimaldi, can you also fill some extra details of your system:
> 
> * Operating system.
> * Docker version.
> * Tutor version.
> * tutor-contrib-codejail version

Operating System: Ubuntu 22.04.4
Docker: 24.0.7
Tutor:  18.1.0
tutor-contrib-codejai: 18.0.0

**Comment by mariajgrimaldi** [comment]
I'll close this issue since one of our suggestions fixed the problem. Thank you!
